version: '3.6'

services:
    client:
        container_name: client
        build:
            context: ./client
            target: watch
        volumes:
            - ./client:/home/node/app

    client_nginx:
        container_name: client_nginx
        image: nginx:stable
        ports:
            - "8070:80"
        volumes:
            - ./client:/app
            - ./docker/client-nginx/site.conf:/etc/nginx/conf.d/default.conf

    server:
        container_name: server
        build:
            context: ./server
        volumes:
            - ./server:/app

    server_nginx:
        container_name: server_nginx
        build:
            context: ./server_nginx
        ports:
            - "8075:80"
        depends_on:
            - server
