version: '3.6'

services:
    client-node:
        build:
            context: .
            dockerfile: ./docker/client-node/Dockerfile
        volumes:
            - ./client:/home/node/app
        command: sh -c 'yarn install && yarn watch'

    client-nginx:
        image: nginx:stable
        ports:
            - "8070:80"
        volumes:
            - ./client:/app
            - ./docker/client-nginx/site.conf:/etc/nginx/conf.d/default.conf

    server-nginx:
        image: nginx:stable
        ports:
            - "8075:80"
        volumes:
            - ./server:/app
            - ./docker/server-nginx/site.conf:/etc/nginx/conf.d/default.conf
