version: '3.6'

services:
    client-node:
        image: node:15.2.1-alpine3.10
        volumes:
            - ./client:/home/node/app
        command: sh -c 'cd /home/node/app && yarn install && yarn watch'

    client-nginx:
        image: nginx:stable
        ports:
            - "8070:80"
        volumes:
            - ./client:/app
            - ./docker/client-nginx/site.conf:/etc/nginx/conf.d/default.conf
